In [15]:
import pandas as pd

df = pd.read_csv("D:/EMG/2eme annee/S2/Programmation python/Projets/netflix-project/data/raw/netflix_shows.csv")

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,language,description,popularity,vote_count,vote_average,budget,revenue,year_added,month_added
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000.0,752600867.0,2010,5
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000.0,839030630.0,2010,7
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000.0,954305868.0,2010,11
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000.0,592461732.0,2010,11
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000.0,494879471.0,2010,3

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32000 entries, 0 to 31999
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       32000 non-null  int64
 1   type          32000 non-null  object
 2   title         32000 non-null  object
 3   director      32000 non-null  object
 4   cast          32000 non-null  object
 5   country       32000 non-null  object
 6   date_added    32000 non-null  object
 7   release_year  32000 non-null  int64
 8   rating        32000 non-null  float64
 9   genres        32000 non-null  object
 10  language      32000 non-null  object
 11  description   32000 non-null  object
 12  popularity    32000 non-null  float64
 13  vote_count    32000 non-null  int64
 14  vote_average  32000 non-null  float64
 15  budget        32000 non-null  object
 16  revenue       32000 non-null  object
 17  year_added    32000 non-null  int64
 18  month_added   32000 non-null  int64
dtypes: float64(3), int64(5), object(11)
memory usage: 4.6+ MB

In [17]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
genres          0
language        0
description     0
popularity      0
vote_count      0
vote_average    0
budget          0
revenue         0
year_added      0
month_added     0
dtype: int64

In [48]:
df["director"] = df["director"].fillna("Unknown")
df["cast"] = df["cast"].fillna("Unknown")
df["genres"] = df["genres"].fillna("Unknown")
df["description"] = df["description"].fillna("Unknown")
df["budget"] = df["budget"].fillna("Unknown")
df["revenue"] = df["revenue"].fillna("Unknown")

In [49]:
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

In [21]:
df["year_added"] = df["date_added"].dt.year
df["month_added"] = df["date_added"].dt.month

In [24]:
df["genres"] = df["genres"].str.split(", ")

In [64]:
import ast

df["genres"] = df["genres"].apply(ast.literal_eval)

In [65]:
type(df["genres"].iloc[0])

list

In [25]:
df["type"] = df["type"].str.lower()

In [33]:
df["budget"] = pd.to_numeric(
    df["budget"], errors="coerce"
)

df["revenue"] = pd.to_numeric(
    df["revenue"], errors="coerce"
)

In [40]:
df = df.drop_duplicates()

In [66]:
df.info()
df.isnull().sum()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29222 entries, 0 to 29221
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       29222 non-null  int64
 1   type          29222 non-null  object
 2   title         29222 non-null  object
 3   director      29222 non-null  object
 4   cast          29222 non-null  object
 5   country       29222 non-null  object
 6   date_added    29222 non-null  datetime64[ns]
 7   release_year  29222 non-null  int64
 8   rating        29222 non-null  float64
 9   genres        29222 non-null  object
 10  language      29222 non-null  object
 11  description   29222 non-null  object
 12  popularity    29222 non-null  float64
 13  vote_count    29222 non-null  int64
 14  vote_average  29222 non-null  float64
 15  year_added    29222 non-null  int64
 16  month_added   29222 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(5), object(8)
memory usage: 3.8+ MB

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,language,description,popularity,vote_count,vote_average,year_added,month_added
0,10192,movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.38,"[Comedy, Adventure, Fantasy, Animation, Family]",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.38,2010,5
1,38757,movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.60,"[Animation, Family, Adventure]",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.60,2010,11
2,10191,movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.80,"[Fantasy, Adventure, Animation, Family]",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.80,2010,3
3,11324,movie,Shutter Island,Martin Scorsese,"Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley,...",United States of America,2010-02-14,2010,8.20,"[Drama, Thriller, Mystery]",en,World War II soldier-turned-U.S. Marshal Teddy...,101.551,24282,8.20,2010,2
4,38575,movie,The Karate Kid,Harald Zwart,"Jaden Smith, Jackie Chan, Taraji P. Henson, We...","China, Hong Kong, United States of America",2010-06-10,2010,6.50,"[Action, Adventure, Drama, Family]",en,Twelve-year-old Dre Parker could have been the...,96.385,6082,6.50,2010,6

In [53]:
(df == "Unknown").sum()

show_id             0
type                0
title               2
director         9616
cast             1011
country             0
date_added          0
release_year        0
rating              0
genres              0
language            0
description      2627
popularity          0
vote_count          0
vote_average        0
budget          14203
revenue         14203
year_added          0
month_added         0
dtype: int64

In [54]:
df = df.drop(columns=["budget", "revenue"])

In [55]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'genres', 'language', 'description',
       'popularity', 'vote_count', 'vote_average', 'year_added',
       'month_added'],
      dtype='object')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29737 entries, 0 to 29736
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       29737 non-null  int64
 1   type          29737 non-null  object
 2   title         29737 non-null  object
 3   director      29737 non-null  object
 4   cast          29737 non-null  object
 5   country       29737 non-null  object
 6   date_added    29737 non-null  datetime64[ns]
 7   release_year  29737 non-null  int64
 8   rating        29737 non-null  float64
 9   genres        29737 non-null  object
 10  language      29737 non-null  object
 11  description   29737 non-null  object
 12  popularity    29737 non-null  float64
 13  vote_count    29737 non-null  int64
 14  vote_average  29737 non-null  float64
 15  year_added    29737 non-null  int64
 16  month_added   29737 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(5), object(8)
memory usage: 3.9+ MB

In [57]:
(df == "Unknown").sum()

show_id            0
type               0
title              2
director        9616
cast            1011
country            0
date_added         0
release_year       0
rating             0
genres             0
language           0
description     2627
popularity         0
vote_count         0
vote_average       0
year_added         0
month_added        0
dtype: int64

In [58]:
df = df[df["title"] != "Unknown"]

In [59]:
df = df[df["title"] != "Unknown"].reset_index(drop=True)

In [60]:
(df == "Unknown").sum()

show_id            0
type               0
title              0
director        9616
cast            1011
country            0
date_added         0
release_year       0
rating             0
genres             0
language           0
description     2627
popularity         0
vote_count         0
vote_average       0
year_added         0
month_added        0
dtype: int64

In [73]:
df = df[df["genres"] != "Unknown"]
df = df[df["genres"] != "Unknown"].reset_index(drop=True)

In [68]:
genres = df["genres"].explode()

In [71]:
top_genres = genres.value_counts().head(10)
top_genres

genres
Drama        13803
Comedy        8570
Animation     3928
Thriller      3585
Action        3118
Crime         3030
Family        2827
Romance       2425
Mystery       2423
Horror        2334
Name: count, dtype: int64

In [74]:
df["genres"] = df["genres"].apply(lambda x: sorted(x))

In [75]:
genres = df["genres"].explode()
top_genres = genres.value_counts()

In [76]:
df["genres"] = df["genres"].apply(lambda x: sorted(x))

In [77]:
df["genres"] = df["genres"].apply(lambda x: tuple(sorted(x)))

In [79]:
df.head(100)

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,language,description,popularity,vote_count,vote_average,year_added,month_added
0,10192,movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.38,"(Adventure, Animation, Comedy, Family, Fantasy)",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.38,2010,5
1,38757,movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.60,"(Adventure, Animation, Family)",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.60,2010,11
2,10191,movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.80,"(Adventure, Animation, Family, Fantasy)",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.80,2010,3
3,11324,movie,Shutter Island,Martin Scorsese,"Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley,...",United States of America,2010-02-14,2010,8.20,"(Drama, Mystery, Thriller)",en,World War II soldier-turned-U.S. Marshal Teddy...,101.551,24282,8.20,2010,2
4,38575,movie,The Karate Kid,Harald Zwart,"Jaden Smith, Jackie Chan, Taraji P. Henson, We...","China, Hong Kong, United States of America",2010-06-10,2010,6.50,"(Action, Adventure, Drama, Family)",en,Twelve-year-old Dre Parker could have been the...,96.385,6082,6.50,2010,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,23631,movie,Machete,"Robert Rodriguez, Ethan Maniquis","Danny Trejo, Michelle Rodriguez, Jessica Alba,...",United States of America,2010-09-01,2010,6.30,"(Action, Comedy, Thriller)",en,After being set-up and betrayed by the man who...,20.986,3327,6.30,2010,9
96,25642,movie,Ben 10 Alien Swarm,Alex Winter,"Ryan Kelley, Galadriel Stineman, Nathan Keyes,...",United States of America,2010-03-12,2010,6.10,"(Action, Adventure, Science Fiction, TV Movie)",en,Ben and a mysterious girl from his past must p...,20.878,343,6.10,2010,3
97,26388,movie,Buried,Rodrigo Cortés,"Ryan Reynolds, José Luis García Pérez, Robert ...","France, Spain, United States of America",2010-09-24,2010,6.60,"(Drama, Mystery, Thriller)",en,Paul is a U.S. truck driver working in Iraq. A...,20.832,2831,6.60,2010,9
98,43939,movie,I'm Still Here,Casey Affleck,"Joaquin Phoenix, Antony Langdon, Carey Perloff...",United States of America,2010-09-10,2010,6.00,"(Comedy, Drama, Music)",en,I'm Still Here is a portrayal of a tumultuous ...,20.803,373,6.00,2010,9
99,63319,movie,Belle épine,Rebecca Zlotowski,"Léa Seydoux, Anaïs Demoustier, Johan Libéreau,...",France,2010-11-10,2010,5.50,"(Drama,)",fr,"After the death of her mother, 17-year-old Pru...",20.789,53,5.50,2010,11

In [80]:
df.to_csv("D:/EMG/2eme annee/S2/Programmation python/Projets/netflix-project/data/processed/netflix_clean.csv", index=False)